# Generated by Django 4.0.1 on 2022-01-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField()),
                ('body', models.FileField(upload_to='user/files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.myprojectbaseuser')),
            ],
        ),
    ]
