# Generated by Django 4.0.1 on 2022-01-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_upload', '0002_alter_flile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
